name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
             docker build ./docker --tag ghcr.io/creepycats/chrome-node17:latest
             docker run ghcr.io/creepycats/chrome-node17:latest
             docker push ghcr.io/creepycats/chrome-node17:latest
